

function toggleBereich() {
    var bereich = document.getElementById("meinBereich");
    if (bereich.style.display === "none") {
      bereich.style.display = "block";
    } else {
      bereich.style.display = "none";
    }
  }

  function toggleBereich2() {
    var bereich = document.getElementById("meinBereich2");
    if (bereich.style.display === "none") {
      bereich.style.display = "block";
    } else {
      bereich.style.display = "none";
    }
  }